### ISSUE TITLE
Link with anchor

### ISSUE THREAD

**Issue by FranklinYu** [RoiEXLab/java-redirect#2]
For example:

http://docs.oracle.com/javase/6/docs/api/javax/swing/JComponent.html#registerKeyboardAction%28java.awt.event.ActionListener,%20java.lang.String,%20javax.swing.KeyStroke,%20int%29

doesn’t work

**Comment by RoiEXLab** [comment]
@franklinyu This issue has been fixed in version 3.1
You should be able to update it now.
